project:
  type: website

website:
  title: "rssdatavisguide"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: docs/introduction.qmd
        text: Guide
        
  sidebar: 
      - title: Guide
        style: floating
        collapse-level: 2
        align: left
        contents:
          - href: docs/introduction.qmd
            text: Introduction
          - href: docs/why-visualise.qmd
            text: Why do we visualise data?
          - href: docs/principles.qmd
            text: Principles of data visualisation
          - href: docs/choosing.qmd
            text: Choosing a visualisation type
          - href: docs/styling.qmd
            text: Styling your visualisation
          - href: docs/tools.qmd
            text: Styling charts for RSS publications
            
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

