project:
  type: website

website:
  title: "Guide to Good Graphics"
  image: RSS_logo_colour.png
  navbar:
    logo: RSS_logo_colour.png
    left:
      - href: index.qmd
        text: Introduction
      - href: howto.qmd
        text: How to use this guide
      - href: docs/index.qmd
        text: The guide
      - href: about.qmd
        text: About the authors

        
  sidebar: 
      - title: Guide
        style: floating
        collapse-level: 2
        align: left
        contents:
          - href: index.qmd
            text: Introduction
          - href: howto.qmd
            text: How to use this guide
          - section: "The guide"
            contents: 
              - href: docs/why-visualise.qmd
                text: Why do we visualise data?
              - href: docs/principles.qmd
                text: Principles of data visualisation
              - href: docs/choosing.qmd
                text: Choosing a visualisation type
              - href: docs/styling.qmd
                text: Styling your visualisation
              - href: docs/tools.qmd
                text: Styling charts for RSS publications
          - href: about.qmd
            text: About the authors
            
  page-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

